### ISSUE TITLE
Tracking snap_manageAccounts permission

### ISSUE THREAD

**Issue by tmpfs** [MetaMask/snaps#579]
This issue is to track the tasks required to land the draft version of the `snap_manageAccounts` permission implementation.

* [ ] Peer review the draft `snap-keyring` implementation, see https://github.com/LavaMoat/snap-keyring/
* [ ] Merge the PR which adds the implementation to `@metamask/rpc-methods`, see #549 
* [ ] Merge the PR which adds the `snap-keyring` to the `keyringController` and activates the `snap_manageAccounts` method implementation, see https://github.com/MetaMask/metamask-extension/pull/14967

In addition we would need to decide on whether the isolation for the managed accounts is acceptable. Currently, accounts are isolated by snap identifier which means that private data is accessible from multiple dapps; for my use case implementing the *threshold signatures* snap this is not the correct behavior and we should work out a strategy for allowing multiple isolation scopes (snap or dapp). For some more discussion about this, see #548.

Related to [SSIP-2](https://github.com/MetaMask/SSIPs/pull/2).

/cc @rekmarks, @ritave
